### ISSUE TITLE
Fix big gap on mobile between the description and icons

### ISSUE THREAD

**Issue by JamieCruwys** [MobileDorset/mobiledorset.github.io#23]
There is a big gap between the description (currently `Mobile Dorset is an informal gathering of mobile developers, designers and anyone with a passion for mobile in Dorset.`) and the icons (currently `Present`, `Drink & Eat` and `Chit Chat`). This is for mobile. After some brief looking into it - it appears that this is due to `min-height: 80%` CSS rule that is applied to the header.

![Mobile Dorset Mobile Issue](https://i.imgur.com/MoID47s.png)

**Comment by hepto** [comment]
You are right - that CSS rule is causing the big gap on smaller widths as the header content scales inside it.  A simple fix is just to remove that rule, and it looks reasonable to me for now, though it might be worth taking an overall look at the mobile experience at some point.

**Comment by hepto** [comment]
Probably worth noting that this will only really show itself on really tall and thin screens, which are quite uncommon in real life.  On normal portrait sizes the header content is actually larger than 80% of the height so the rule is not applied.

**Comment by hepto** [comment]
Potential quick fix in c11ace70ada8b7d95bf0ae4d3274a1ed6176c94d.

**Comment by clockworkant** [comment]
fixed in #27
