### ISSUE TITLE
Burger menu does not work on mobile

### ISSUE THREAD

**Issue by JamieCruwys** [MobileDorset/mobiledorset.github.io#25]
When you tap the burger menu on mobile, nothing happens.

**Comment by hepto** [comment]
This is because the Bootstrap collapse JS is not wired in.  Fixed in commit 9834bb50b2c074edbd15d7866e95b113580c22c8 on branch 25-fix-burger-menu.

I haven't looked at the look & feel of viewing the site at a mobile breakpoint, just fixed the burger menu.

**Comment by clockworkant** [comment]
fixed by #26
